import os

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from dotenv import load_dotenv

from azure.identity import DefaultAzureCredential
from azure.ai.projects import AIProjectClient

load_dotenv()

# --------------------------------------------------
# Configuration
# --------------------------------------------------

FOUNDRY_ENDPOINT = os.environ["FOUNDRY_PROJECT_ENDPOINT"]

AGENT_1_NAME = "chitkara-enterprise-knowlegde-agent"
AGENT_1_VERSION = "14"

AGENT_2_NAME = "chitkara-answer-formatter"
AGENT_2_VERSION = "4"

# --------------------------------------------------
# Foundry client
# --------------------------------------------------

credential = DefaultAzureCredential()

project_client = AIProjectClient(
    endpoint=FOUNDRY_ENDPOINT,
    credential=credential,
)

# Agent 1 - RAG / Knowledge Agent
agent_1_client = project_client.get_openai_client(
    agent_name=AGENT_1_NAME
)

# Agent 2 - Formatting Agent
agent_2_client = project_client.get_openai_client(
    agent_name=AGENT_2_NAME
)

# --------------------------------------------------
# FastAPI
# --------------------------------------------------

app = FastAPI(title="Chitkara Enterprise Knowledge API")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=False,
    allow_methods=["*"],
    allow_headers=["*"],
)


# --------------------------------------------------
# Request models
# --------------------------------------------------

class ChatRequest(BaseModel):
    message: str
    conversation_id: str | None = None
    foundry_conversation_id: str | None = None


# --------------------------------------------------
# Routes
# --------------------------------------------------

@app.get("/health")
def health():
    return {
        "status": "ok",
        "agent": AGENT_1_NAME,
        "agent_version": AGENT_1_VERSION,
        "formatter": AGENT_2_NAME,
        "formatter_version": AGENT_2_VERSION,
    }


@app.post("/api/chat")
def chat(request: ChatRequest):

    # --------------------------------------------------
    # 1. Get or create Foundry conversation
    # --------------------------------------------------

    foundry_conversation_id = request.foundry_conversation_id

    if not foundry_conversation_id:
        conversation = agent_1_client.conversations.create()
        foundry_conversation_id = conversation.id

    # --------------------------------------------------
    # 2. Agent 1 — RAG / Knowledge Agent
    # --------------------------------------------------

    agent_1_response = agent_1_client.responses.create(
        conversation=foundry_conversation_id,
        input=request.message,
    )

    raw_answer = agent_1_response.output_text

    # --------------------------------------------------
    # 3. Agent 2 — Formatting Agent
    # --------------------------------------------------

    formatter_prompt = f"""
You are the final answer formatting agent.

You receive the response generated by a separate
knowledge/RAG agent.

Your job is to turn that response into a clean,
concise and user-friendly final answer.

Rules:

1. Do NOT add new facts.
2. Do NOT use outside knowledge.
3. Do NOT invent information.
4. Do NOT change the factual meaning of the answer.
5. Preserve all important factual information.
6. Improve only formatting, structure, readability
   and conciseness.
7. Use Markdown when appropriate.
8. Use headings, bullet points, numbered lists or
   tables when they improve readability.
9. Remove internal citation/source markers such as:
   【...†source】
   【...】
   [source: ...]
   [Source: ...]
10. Do not mention that citations or source markers
    were removed.
11. Do not add new options or choices that were not
    present in the original answer.
12. If the knowledge agent says that information is
    unavailable or outside its scope, preserve that
    meaning.
13. Return ONLY the final formatted answer.

Knowledge agent response:

{raw_answer}
"""

    agent_2_response = agent_2_client.responses.create(
        input=formatter_prompt
    )

    final_answer = agent_2_response.output_text

    # --------------------------------------------------
    # 4. Return final answer + Foundry conversation ID
    # --------------------------------------------------

    return {
        "response": final_answer,
        "foundry_conversation_id": foundry_conversation_id,
        "agent": AGENT_1_NAME,
        "agent_version": AGENT_1_VERSION,
        "formatter": AGENT_2_NAME,
        "formatter_version": AGENT_2_VERSION,
    }
